#!/bin/bash
set -e

fresh_environment() {
	# will recreate and activate a fresh python environment
	# usage: fresh_environment requirements.txt

	>&2 echo "creating & activating a fresh environment from $1..."
	
	envir="_testing-environment"
	rm -rf "$envir"
	python3 -m venv "$envir"
	source "$envir/bin/activate"
	pip install -r "$1"

}


wait_for_keypress() {
	while true
	do
		read -n 1
		if [ $? = 0 ]
		then
			return 0
		fi
	done
}

mask_for_privacy()
{
	sed -e 's/00:16:53:b.:..:../00:16:53:bX:XX:XX/g' \
	    -e 's/\(:[0-9A-Fa-f]\{2\}\)\{5\}/:XX:XX:XX:XX:XX/g' \
	    -i "$1"
}

for variant in pygatt gatt gattlib bluepy 
do
	mkdir -p "results"

	fresh_environment "requirements.$variant.txt"
	pip freeze > "results/$variant.pip-freeze.txt"

	>&2 echo "---------------------------------------------------------------------------------"
	>&2 echo "Ready to try using \"$variant\". Please activate the Lego Hub & press a key here!"
	wait_for_keypress

	script -c "python list-peripherals.py" \
		--output-limit 1000000 \
		-t"results/$variant.timing" "results/$variant.script"

	mask_for_privacy "results/$variant.timing"
	mask_for_privacy "results/$variant.script"
done
